[package]
name = "lab4-static-shaders"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.29"
wgpu = "0.19"
env_logger = "0.10"
log = "0.4"
bytemuck = { version = "1.14", features = ["derive"] }
anyhow = "1.0"
tobj = "4.0"
cgmath = "0.18"
pollster = "0.3"
rand = "0.8"
